schema_version = "1.0.0"

id = "ba_toolkit_for_blender"
version = "0.2.0"
name = "Blue Archive Toolkit for Blender"
tagline = "Blue Archive model import, texture fix and auto mouth rigging"
description = "This toolkit is a helpful Blender add‑on for creating 3D animations using Blue Archive models. It assists with model import, attempts to fix texture issues, and automatically separates the mouth mesh then binds it to a mouth controller, enabling faster animation setup."
maintainer = "AkagawaTsurunaki"
type = "add-on"

blender_version_min = "4.5.6"

license = [
    "MIT",
]

tags = ["Material"]
